blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/ajay-dhangar/job-board/discussions
    about: Ask general questions or start discussions about the project.
